# 1

In [1]:
import numpy as np

In [2]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

In [3]:
# Addition of two array
print(A + B)

[[3 1]
 [3 5]]


In [4]:
# Addition of two array
print(np.add(A, B))

[[3 1]
 [3 5]]


In [5]:
# Elementwise product
print(A * B)

[[2 0]
 [0 4]]


In [6]:
# Transpose of B array
print(A.dot(B))

[[5 4]
 [3 4]]


In [7]:
# Form 1-d array
print(A.flatten())

[1 1 0 1]


In [8]:
# Boolean of Matrix B. True for elements less than 3
print(B < 3)

[[ True  True]
 [False False]]


In [9]:
# Sum of all elements of A
print(A.sum())

3


In [10]:
# Sum of each column
print(A.sum(axis = 0))

[1 2]


In [11]:
# Sum of each row
print(A.sum(axis = 1))

[2 1]


In [12]:
# Cumulative sum along each row
print(A.cumsum(axis = 1))

[[1 2]
 [0 1]]


In [13]:
# Min value of all elements
print(A.min())

0


In [14]:
# Max value of all elements
print(A.max())

1


In [15]:
# Exponential
print(np.exp(B))

[[ 7.3890561   1.        ]
 [20.08553692 54.59815003]]


In [16]:
# Squre root
print(np.sqrt(B))

[[1.41421356 0.        ]
 [1.73205081 2.        ]]


In [17]:
# Position of min value of elements 
print(A.argmin())

2


In [18]:
# Position of max value of elements
print(A.argmax())

0


In [19]:
# Member of a array in (1,1) position
print(A[1, 1])

1


# 2

In [20]:
# Create array a
a = np.arange(4)**3  

In [21]:
# Member of a array in 2nd position
print(a)
print(a[2])

[ 0  1  8 27]
8


In [22]:
# Reversed a
print(a[::-1])

[27  8  1  0]


In [23]:
# Same as a[1,:,:] or a[1]
print(a[1,...])

1


In [24]:
# a with values greater than 5
print(a[a>5])

[ 8 27]


In [25]:
# Assign x with 4 values of a
x = a[0:4]
print(x)

[ 0  1  8 27]


In [26]:
# Change the values of x to 99 which will change the 4 values of a also.
x[:] = 99
print(x)

[99 99 99 99]
